### ISSUE TITLE
Kuberentes Issue

### ISSUE THREAD

**Issue by ranlandau** [julianxhokaxhiu/docker-woocommerce#5]
Hi,

Building this docker, as is.
exporting as 80, 443 using K8s Service NodePort.

Doesn't work.

> root@-demostores-woo-75d7996588-nvxlv:/var/www/html# 
root@-demostores-woo-75d7996588-nvxlv:/var/www/html# curl 127.0.0.1

"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html>
"

**Comment by julianxhokaxhiu** [comment]
Hi,

sorry for the late reply. You need to mount a volume in that path in order to see something.

Otherwise that will be given. That's the default config of the php apache docker container.

Cheers,
Julian
